# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0004_auto_20170802_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheckresult',
            name='consecutive_failures',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
